# Generated by Django 4.2 on 2023-07-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=60)),
                ("product_desc", models.CharField(max_length=200)),
                ("product_pub_date", models.DateField()),
            ],
        ),
    ]
