# Generated by Django 4.2 on 2023-08-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="products",
            name="subcategory",
            field=models.CharField(default="", max_length=200),
        ),
    ]
