# Generated by Django 4.2 on 2023-08-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0002_products_category_products_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(default="", upload_to="myweb/images"),
        ),
    ]
