# Generated by Django 4.2 on 2023-08-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0003_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(default="", upload_to="images"),
        ),
    ]
