# Generated by Django 4.2 on 2023-08-03 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0004_alter_products_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="id",
        ),
        migrations.AddField(
            model_name="products",
            name="product_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
