# Generated by Django 4.2 on 2023-08-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0005_remove_products_id_products_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("contact_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("phoneno", models.CharField(default="", max_length=60)),
                ("email", models.CharField(default="", max_length=50)),
                ("desc", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
