# Generated by Django 4.2 on 2023-08-05 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0006_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name_plural": "Products"},
        ),
    ]
