# Generated by Django 4.2 on 2023-09-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0007_alter_products_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mechant_id", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("pincode", models.IntegerField()),
                ("phoneno", models.CharField(default="", max_length=60)),
                ("email", models.CharField(default="", max_length=50)),
                ("shippingadd", models.CharField(max_length=50)),
                ("billingadd", models.CharField(max_length=50)),
                ("desc", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
