# Generated by Django 4.2 on 2023-09-01 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0008_merchant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="mechant_id",
        ),
    ]
