# Generated by Django 4.2 on 2023-09-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0009_remove_merchant_mechant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="billingadd",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="country",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="desc",
            field=models.CharField(default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="email",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="phoneno",
            field=models.CharField(default="", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="pincode",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="shippingadd",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="surname",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
